name: OnMMy Project Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  issues:
    types: [opened]

jobs:
  auto-assign-issues:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Auto-assign issue
        uses: actions/auto-assign@v1
        with:
          assignees: "你的GitHub用户名"  # 可以改成团队成员
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  python-ci:
    runs-on: ubuntu-latest
    if: github.event_name != 'issues'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          if [ -f tests/test_main.py ]; then pytest tests/; else echo "No tests found"; fi

      - name: Build EXE
        run: |
          pip install pyinstaller
          pyinstaller --onefile run_onmmy.py --name OnMMy-v.1.0.0 --distpath dist

  upload-release-artifact:
    runs-on: ubuntu-latest
    needs: python-ci
    if: github.event_name != 'issues'
    steps:
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: OnMMy-v.1.0.0
          path: dist/OnMMy-v.1.0.0.exe
